gsb_covoit_homepage:
    path:     /acceuil
    defaults: { _controller: GSBCovoitBundle:Covoit:index }

gsb_covoit_trajet:
    path:     /trajet/{id}
    defaults:
      _controller: GSBCovoitBundle:Covoit:trajet
    requirements:
      id: \d+

gsb_covoit_salarie:
    path:     /salarie/{id}
    defaults:
      _controller: GSBCovoitBundle:Covoit:salarie
    requirements:
      id: \d+

gsb_covoit_inscription:
    path:   /inscription
    defaults: {_controller: GSBCovoitBundle:Login:inscription}

gsb_covoit_login:
    path:   /login
    defaults: {_controller: GSBCovoitBundle:Login:login }
