gsb_covoit:
    resource: "@GSBCovoitBundle/Resources/config/routing.yml"
    prefix:   /
<<<<<<< HEAD

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
=======
>>>>>>> refs/remotes/origin/master
